Output example/tapes/output/multi_select.gif

Set FontSize 14
Set Width 700
Set Height 380
Set Theme "Dracula"
Set PlaybackSpeed 1.0

Type "fvm dart run tool/bin/multi_select.dill"
Enter
Sleep 800ms
Down
Sleep 300ms
Down
Sleep 300ms
Space
Sleep 300ms
Up
Sleep 300ms
Space
Sleep 300ms
Down
Sleep 300ms
Down
Sleep 300ms
Down
Sleep 300ms
Space
Sleep 400ms
Type "a"
Sleep 600ms
Type "a"
Sleep 600ms
Down
Sleep 300ms
Space
Sleep 300ms
Enter
Sleep 1s
Type "q"
Sleep 500ms
